openapi: 3.0.1
info:
  title: Examples in section 1
  version: 1.0.0
components:
  schemas:
    CountryCode:
      type: string
      example: ITA
    Country:
      type: object
      properties:
        identifier:
          $ref: "#/components/schemas/CountryCode"
        name:
          type: string
      example:
        identifier: ITA
        name: Italy
    CountryBlankNode:
      x-jsonld-type: Country
      x-jsonld-context:
        "@vocab": "https://schema.org/"
      type: object
      properties:
        identifier:
          $ref: "#/components/schemas/CountryCode"
        name:
          type: string
      example:
        identifier: ITA
        name: Italy
    CountryURI:
      x-jsonld-type: Country
      x-jsonld-context:
        "@vocab": "https://schema.org/"
        identifier: "@id"
        "@base": "http://publications.europa.eu/resource/authority/country/"
      type: object
      properties:
        identifier:
          $ref: "#/components/schemas/CountryCode"
        name:
          type: string
      example:
        identifier: ITA
        name: Italy
      x-rdf: |-
        @prefix : <https://schema.org/> .
        @prefix country: <http://publications.europa.eu/resource/authority/country/> .

        country:ITA a :Country ;
            :name "Italy" .
    Person:
      description: |-
        A person where nationality
        is represented as a country code
        with @vocab mapping.
      x-jsonld-type: Person
      x-jsonld-context:
        "@vocab": "https://schema.org/"
        nationality:
          "@type": "@vocab"
          "@context":
            "@vocab": "http://publications.europa.eu/resource/authority/country/"
      type: object
      properties:
        givenName:
          type: string
        familyName:
          type: string
        nationality:
          $ref: "#/components/schemas/CountryCode"
      example:
        givenName: John
        familyName: Doe
        nationality: ITA
      x-rdf: |-
        @prefix : <https://schema.org/> .

        [] a :Person ;
            :familyName "Doe" ;
            :givenName "John" ;
            :nationality <http://publications.europa.eu/resource/authority/country/ITA> .
    NestedPerson:
      x-jsonld-type: Person
      x-jsonld-context:
        "@vocab": "https://schema.org/"
      type: object
      properties:
        givenName:
          type: string
        familyName:
          type: string
        nationality:
          $ref: "#/components/schemas/CountryURI"
      example:
        givenName: John
        familyName: Doe
        nationality:
          identifier: ITA
          name: Italy
      x-rdf: |-
        @prefix : <https://schema.org/> .
        @prefix country: <http://publications.europa.eu/resource/authority/country/> .

        [] a :Person ;
            :familyName "Doe" ;
            :givenName "John" ;
            :nationality country:ITA .

        country:ITA a :Country ;
            :name "Italy"
            .
